make Carousel slide and drag controllable
helpwave/web pull request #1088
Opened 2024-09-04 15:24 UTC by DasProffi

## Which issues does this pull request close?
closes #1071

## [OPTIONAL] Give testing instructions to reviewers
Look at the preview of out landing page on the start screen there is a slider

2024-09-05 20:06 UTC, MaxSchaefer approved these changes

2024-09-05 20:06 UTC, MaxSchaefer commented on lib/components/layout/Carousel.tsx
> +  const cardsPerSecond: number = 4 // in ms per card, musst be != 0
```suggestion
  const cardsPerSecond: number = 4 // in ms per card, must be != 0
```

2024-09-05 20:06 UTC, MaxSchaefer approved these changes

2024-09-05 21:41 UTC, use-to requested changes
Can we add a slide transition of 5s.
And can we make it repetitive?

2024-09-11 20:20 UTC, DasProffi commented
Changes in #1092

2024-09-11 20:32 UTC, merged