add OrganizationTile
helpwave/web pull request #122
Opened 2023-03-25 13:43 UTC by DasProffi

closes #100
![Unbenannt](https://user-images.githubusercontent.com/67233923/227720859-e7309e37-101f-47cd-a6ce-80e7396519ad.PNG)

2023-03-25 13:50 UTC, JannikWibker approved these changes
as far as I can tell from the screenshot provided the font sizes and font weights might need a little bit of work, this could also just a design issue, but I think we can merge this and do a bit of clean up later on

2023-03-25 14:24 UTC, MaxSchaefer requested changes
I've got the following Bug (no AvatarGroup).

<img width="1680" alt="Bildschirm­foto 2023-03-25 um 3 23 12 PM" src="https://user-images.githubusercontent.com/40192999/227723070-a6d168ff-6c1a-457a-9b16-6328559601f3.png">

```tsx
import type { NextPage } from 'next'
import { OrganizationTile } from '../components/OrganizationTile'

const Test: NextPage = () => {
  return (
    <div className={'flex'}>
      <OrganizationTile organization={{
        email: 'info@ukm.de',
        longName: 'Uniklinikum Münster',
        shortName: 'UKM',
        members: [
          {
            name: 'One Two',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Three Four',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Five Six',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Seven Eight',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Nine Ten',
            avatarURL: 'https://source.boringavatars.com/'
          },
        ],
        wards: [
          { name: 'ICU#1' }, { name: 'ICU#2' }
        ]
      }}/>
      <OrganizationTile organization={{
        email: 'info@ukm.de',
        longName: 'Uniklinikum Münster',
        shortName: 'UKM',
        members: [
          {
            name: 'One Two',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Three Four',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Five Six',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Seven Eight',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Nine Ten',
            avatarURL: 'https://source.boringavatars.com/'
          },
        ],
        wards: [
          { name: 'ICU#1' }, { name: 'ICU#2' }
        ]
      }}/>
      <OrganizationTile organization={{
        email: 'info@ukm.de',
        longName: 'Uniklinikum Münster',
        shortName: 'UKM',
        members: [
          {
            name: 'One Two',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Three Four',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Five Six',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Seven Eight',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Nine Ten',
            avatarURL: 'https://source.boringavatars.com/'
          },
        ],
        wards: [
          { name: 'ICU#1' }, { name: 'ICU#2' }
        ]
      }}/>
      <OrganizationTile organization={{
        email: 'info@ukm.de',
        longName: 'Uniklinikum Münster',
        shortName: 'UKM',
        members: [
          {
            name: 'One Two',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Three Four',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Five Six',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Seven Eight',
            avatarURL: 'https://source.boringavatars.com/'
          },
          {
            name: 'Nine Ten',
            avatarURL: 'https://source.boringavatars.com/'
          },
        ],
        wards: [
          { name: 'ICU#1' }, { name: 'ICU#2' }
        ]
      }}/>
    </div>
  )
}

export default Test
```

2023-03-25 14:24 UTC, MaxSchaefer commented on tasks/components/OrganizationTile.tsx
> +        {organization.wards.map(value => value.name).join(', ')}
We should limit the amount of wards, as we already do with the Members in the AvatarGroup.

2023-03-26 20:07 UTC, MaxSchaefer requested changes

2023-03-26 20:07 UTC, MaxSchaefer commented on tasks/components/OrganizationTile.tsx
> +  displayedAvatars?: number,
This should be `maxShownWards` also to stay consistent with the `AvatarGroup`.

2023-03-26 20:08 UTC, MaxSchaefer commented
> I've got the following Bug (no AvatarGroup).
> 
> <img alt="Bildschirm­foto 2023-03-25 um 3 23 12 PM" width="1680" src="https://user-images.githubusercontent.com/40192999/227723070-a6d168ff-6c1a-457a-9b16-6328559601f3.png">
> 
> ```tsx
> import type { NextPage } from 'next'
> import { OrganizationTile } from '../components/OrganizationTile'
> 
> const Test: NextPage = () => {
>   return (
>     <div className={'flex'}>
>       <OrganizationTile organization={{
>         email: 'info@ukm.de',
>         longName: 'Uniklinikum Münster',
>         shortName: 'UKM',
>         members: [
>           {
>             name: 'One Two',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Three Four',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Five Six',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Seven Eight',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Nine Ten',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>         ],
>         wards: [
>           { name: 'ICU#1' }, { name: 'ICU#2' }
>         ]
>       }}/>
>       <OrganizationTile organization={{
>         email: 'info@ukm.de',
>         longName: 'Uniklinikum Münster',
>         shortName: 'UKM',
>         members: [
>           {
>             name: 'One Two',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Three Four',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Five Six',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Seven Eight',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Nine Ten',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>         ],
>         wards: [
>           { name: 'ICU#1' }, { name: 'ICU#2' }
>         ]
>       }}/>
>       <OrganizationTile organization={{
>         email: 'info@ukm.de',
>         longName: 'Uniklinikum Münster',
>         shortName: 'UKM',
>         members: [
>           {
>             name: 'One Two',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Three Four',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Five Six',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Seven Eight',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Nine Ten',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>         ],
>         wards: [
>           { name: 'ICU#1' }, { name: 'ICU#2' }
>         ]
>       }}/>
>       <OrganizationTile organization={{
>         email: 'info@ukm.de',
>         longName: 'Uniklinikum Münster',
>         shortName: 'UKM',
>         members: [
>           {
>             name: 'One Two',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Three Four',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Five Six',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Seven Eight',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>           {
>             name: 'Nine Ten',
>             avatarURL: 'https://source.boringavatars.com/'
>           },
>         ],
>         wards: [
>           { name: 'ICU#1' }, { name: 'ICU#2' }
>         ]
>       }}/>
>     </div>
>   )
> }
> 
> export default Test
> ```

Issue fixed! Thanks 👍

2023-03-26 20:41 UTC, MaxSchaefer approved these changes

2023-03-27 11:11 UTC, merged