Fix code style
helpwave/web pull request #123
Opened 2023-03-25 17:36 UTC by JannikWibker

The code style got pretty out of control as of recently and our current linting setup isn't detecting it. Thus this PR adds prettier which is much stricter in enforcing and fixing coding style issues.

2023-03-26 20:17 UTC, MaxSchaefer requested changes
My two cents; We should keep:
- Commas overall (especially for `type`)
- Trailing commas, to prevent unnecessary git additions

2023-03-26 20:17 UTC, MaxSchaefer commented on tasks/pages/forgot-password.tsx
> +  return <div>not sure how this is going to look or even work, just a placeholder right now</div>
We should at least stick with the leading and trailing brackets.

2023-03-27 12:10 UTC, JannikWibker commented
@MaxSchaefer I kind of agree with both your comments, but there is one problem with this:
- prettier is pretty opinionated and doesn't really allow for rules to be enforced in a non-strict way; meaning if you "allow" trailing commas you need them everywhere, there is no in between and taking that into account i'm more on the "against"-side when it comes to trailing commas
- prettier is light years ahead of other code formatting and linting tools, I used to dislike prettier because of the highly opinionated and non-configurable nature but have grown to rely on it really much as no other tool detects and fixes this many issues; thus not using prettier is in my opinion not really an option

2023-03-30 22:04 UTC, MaxSchaefer commented
> @MaxSchaefer I kind of agree with both your comments, but there is one problem with this:
> 
> * prettier is pretty opinionated and doesn't really allow for rules to be enforced in a non-strict way; meaning if you "allow" trailing commas you need them everywhere, there is no in between and taking that into account i'm more on the "against"-side when it comes to trailing commas
> * prettier is light years ahead of other code formatting and linting tools, I used to dislike prettier because of the highly opinionated and non-configurable nature but have grown to rely on it really much as no other tool detects and fixes this many issues; thus not using prettier is in my opinion not really an option

We should not adopt code styles because the tools cannot be configured to our liking. I've skimmed over the changes, with a stricter configuration, ESLint should be able to handle this as well.

2023-05-10 12:08 UTC, use-to commented
Houston, we have a problem!

2023-05-10 12:08 UTC, closed without merging