add room list
helpwave/web pull request #156
Opened 2023-04-07 14:22 UTC by DasProffi

closes #138

2023-04-07 20:41 UTC, use-to requested changes

2023-04-07 20:41 UTC, use-to commented on tasks/components/RoomList.tsx
> +                    <div className={tw('flex flex-row items-center w-1/2 min-w-[50px]')}>
Can we make this a little bit wider, please?

2023-04-07 21:48 UTC, MaxSchaefer approved these changes

2023-04-08 09:35 UTC, use-to approved these changes

2023-04-08 10:24 UTC, merged