update header and add page component
helpwave/web pull request #177
Opened 2023-04-11 20:06 UTC by DasProffi

closes #75

2023-04-11 20:08 UTC, DasProffi commented
Either create a new issue for adding the breadcrumbs to the header or do this in this PR after #176 is closed

2023-04-12 18:38 UTC, use-to requested changes
Created new issue #183

2023-04-12 18:38 UTC, use-to commented on tasks/pages/contact.tsx
>        />
Thats duplicated in `/contact`

2023-04-12 18:38 UTC, use-to commented on tasks/pages/organizations/[uuid].tsx
> +      )]}
Maybe we should try to implement a way to skip the usage of the `BreadCrumb` component on the actual pages/views.

One simple idea:
1. Create an additional attribute/parameter passing the current navigation stack
2. Prepend the `BreadCrumb`-component to the internal/private `leftSide` array.

2023-04-12 18:38 UTC, use-to commented on tasks/pages/organizations/[uuid].tsx
> +      )]}
This would increase the developer experience (such as readability)!

2023-04-12 21:49 UTC, use-to approved these changes
Alright. No further questions your honor...

2023-04-13 08:18 UTC, merged