feat: replace favicon.ico with favicon.svg
helpwave/web pull request #184
Opened 2023-04-12 19:31 UTC by florian-sabonchi

2023-04-12 20:03 UTC, MaxSchaefer requested changes

2023-04-12 20:03 UTC, MaxSchaefer commented on tasks/public/favicon.png
Is there an `.svg` version available? Use that instead.

2023-04-12 22:08 UTC, use-to commented on tasks/public/favicon.png
There should be a version at least in figma (so just export it as `.svg`) or just take a look at [helpwave/helpwave](https://github.com/helpwave/helpwave/tree/main/assets/logo). @florian-sabonchi

2023-04-13 18:33 UTC, use-to requested changes
can we please make this bigger?

2023-04-13 20:49 UTC, use-to approved these changes

2023-04-13 22:09 UTC, MaxSchaefer approved these changes

2023-04-14 18:28 UTC, merged