fix: use consistent title
helpwave/web pull request #204
Opened 2023-04-15 20:47 UTC by MaxSchaefer

Use `helpwave tasks` or the suffix `~ helpwave tasks`

2023-04-15 21:46 UTC, florian-sabonchi reviewed
I think we should vote again whether to take a pipe or a tilde

2023-04-16 10:50 UTC, DasProffi requested changes

2023-04-16 10:50 UTC, DasProffi commented on tasks/pages/profile.tsx
> -        <title>Settings</title>
profile should be translated

2023-04-16 10:50 UTC, DasProffi commented on tasks/pages/settings.tsx
> -        <title>Settings</title>
settings needs to be translated

2023-04-16 10:52 UTC, DasProffi commented
Rather than hardcoding the suffix on every page we should use a function to wrap the name of the page
```
const titleWrapper = (title: string) => title + '~ helpwave tasks'
```
This should allow us to easily modify it

2023-04-16 19:32 UTC, use-to commented on tasks/pages/profile.tsx
> -        <title>Settings</title>
profile page is legacy code #183

2023-04-16 21:06 UTC, MaxSchaefer commented
@DasProffi @florian-sabonchi
` ~ ` yes or no? The alternatives are ` | ` or ` - `.

2023-04-17 11:00 UTC, DasProffi approved these changes

2023-04-17 17:52 UTC, merged