add reusable modal
helpwave/web pull request #206
Opened 2023-04-15 23:07 UTC by DasProffi

closes #199

2023-04-16 19:30 UTC, use-to requested changes
1. modal overlay - click event (dismiss function) should be optional
2. modal overlay - background should be darker
3. fix `onClick`-event on actual modal container (currently triggers `onClose`)

2023-04-17 18:02 UTC, JannikWibker commented on tasks/components/modals/Modal.tsx
could also be moved to `lib/`

2023-04-17 18:02 UTC, JannikWibker commented on tasks/components/modals/ConfirmDialog.tsx
> +            onClose('decline')
I'd vouch for having individual callbacks for each action (`'onDecline'`, `onAccept` or `onConfirm`, `onClose`)

But I'm open to discussing this; if there is something specific this allows I'm all for it

2023-04-17 18:04 UTC, use-to commented on tasks/components/modals/Modal.tsx
I would say there are many components we could move to the `lib/` directory.
Maybe we should do it later on?

2023-04-17 20:11 UTC, DasProffi commented on tasks/components/modals/Modal.tsx
I will make an issue for that #212

2023-04-18 09:00 UTC, use-to approved these changes

2023-04-18 11:36 UTC, merged