fix: adopt react library for lucide svg icons
helpwave/web pull request #244
Opened 2023-04-20 11:16 UTC by rajarshisamaddar

The Lucide react library icons have been implemented in this pull request, replacing all the existing SVG icons.

This resolves issue #205 regarding the adoption of the Lucide react library for SVG icons in the application.

Testing instructions:
1. To test, please ensure that all required packages specified in the package.json file are installed.
2. Then, thoroughly browse the web application to verify the icons are functioning properly.

2023-04-20 11:23 UTC, use-to requested changes
Our linter grumbles a bit here.
Use `pnpm run lint` locally. @rajarshisamaddar

2023-04-20 11:39 UTC, rajarshisamaddar commented
> Our linter grumbles a bit here. Use `pnpm run lint` locally. @rajarshisamaddar

@use-to I'm really sorry I'm not aware of this thing can you please explain what is the problem maybe you can share some resources to learn from there about this?

2023-04-20 11:52 UTC, DasProffi commented
> > Our linter grumbles a bit here. Use `pnpm run lint` locally. @rajarshisamaddar
> 
> @use-to I'm really sorry I'm not aware of this thing can you please explain what is the problem maybe you can share some resources to learn from there about this?

A linter is a tool/script that checks the formatting of the code. Running `pnpm run lint` outputs all lines that are malformed according to our code style. You have to apply changes to all lines that are marked with an error.

How it works can be found here: https://www.npmjs.com/package/eslint

But you only need to run the command locally and change the code lines marked with a lint error

2023-04-20 19:55 UTC, MaxSchaefer requested changes

2023-04-20 19:55 UTC, MaxSchaefer commented on tasks/components/OrganizationMemberList.tsx
> +import { ChevronDown as Dropdown } from 'lucide-react'
We should avoid using `as`and should stick with the default naming of `lucide-react` to not confuse people in the future when they come across the icons.

2023-04-21 07:10 UTC, rajarshisamaddar commented
@use-to @MaxSchaefer  all the request changes and checks are passed.

2023-04-21 15:02 UTC, DasProffi requested changes

2023-04-21 15:02 UTC, DasProffi commented on tasks/components/Pagination.tsx
> +import { ChevronRight } from 'lucide-react'
```suggestion
import { ChevronLast, ChevronLeft, ChevronFirst, ChevronRight } from 'lucide-react'
```

2023-04-21 19:01 UTC, MaxSchaefer approved these changes

2023-04-22 05:06 UTC, rajarshisamaddar commented
@MaxSchaefer is there any task left to merge this pull request?

2023-04-22 09:43 UTC, MaxSchaefer approved these changes

2023-04-22 09:44 UTC, MaxSchaefer commented
@use-to you requested changes. Can you revisit this pr please?

2023-04-22 09:48 UTC, use-to approved these changes

2023-04-22 10:24 UTC, merged