Issue/27 landing page
helpwave/web pull request #30
Opened 2022-12-10 19:49 UTC by Florian-Sabonchi

First draft for landing Page with Contact Page

2022-12-10 20:15 UTC, JannikWibker requested changes
`Module not found: Can't resolve '../components/Body'`

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/styles/globals.css
> +}
use the tailwind config instead: https://tailwindcss.com/docs/theme

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/components/Navbar.tsx
> +               xmlns="http://www.w3.org/2000/svg">
xmlns attributes can be removed

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/components/Footer.tsx
> +            </div>
this is **really** repetitive, use a custom component and use it to map over an array

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/components/Footer.tsx
> +      </div>
these logos shouldn't be loaded cross domains

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/components/ContactForm.tsx
> +              email</label>
don't know if we want to deal with a lot of different screen sizes at the moment; maybe better to not have any kind of media-queries in here at this time

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/components/Carousel.tsx
> +          <div className="flex h-96" data-carousel-item="active">
`id="carouselExampleCrossfade"` as well as some of the classnames aren't used for anything -> remove

(this applies to other files as well)

2022-12-10 20:15 UTC, JannikWibker commented on landing-page/pages/contact.tsx
> +      <ContactForm></ContactForm>
use `<Navbar />` instead of `<Navbar></Navbar>`, same for `ContactForm`

2022-12-10 20:17 UTC, JannikWibker commented
PRs doing any UI work should always include a screenshot

2022-12-11 13:01 UTC, Florian-Sabonchi commented
![image](https://user-images.githubusercontent.com/54689374/206905136-86081086-51b4-4ffe-95bd-ed47dd785df5.png)

2022-12-11 13:02 UTC, Florian-Sabonchi commented
![image](https://user-images.githubusercontent.com/54689374/206905174-7cd8920d-aafb-41de-949b-c48a2e9dcb0d.png)

2022-12-13 20:36 UTC, use-to commented
@Florian-Sabonchi I really like the affort you're putting into this - keep it up!
<details>
  <summary>This is the cloudflare pages log</summary>
```
12:22:42.076 | Cloning repository...
-- | --
12:22:43.008 | From https://github.com/helpwave/web
12:22:43.008 | * branch            03a2dfb44e6b2ff6e998469b7c8c9183dc725a01 -> FETCH_HEAD
12:22:43.009 |  
12:22:43.075 | HEAD is now at 03a2dfb feat: code review
12:22:43.076 |  
12:22:43.227 |  
12:22:43.256 | Success: Finished cloning repository files
12:22:43.927 | Installing dependencies
12:22:43.939 | Python version set to 2.7
12:22:47.436 | v12.18.0 is already installed.
12:22:48.675 | Now using node v12.18.0 (npm v6.14.4)
12:22:48.902 | Started restoring cached build plugins
12:22:48.918 | Finished restoring cached build plugins
12:22:49.418 | Attempting ruby version 2.7.1, read from environment
12:22:53.044 | Using ruby version 2.7.1
12:22:53.418 | Using PHP version 5.6
12:22:53.582 | 5.2 is already installed.
12:22:53.610 | Using Swift version 5.2
12:22:53.610 | Started restoring cached node modules
12:22:53.625 | Finished restoring cached node modules
12:22:53.876 | Installing NPM modules using NPM version 6.14.4
12:23:12.994 |  
12:23:12.995 | > core-js-pure@3.26.1 postinstall /opt/buildhome/repo/node_modules/core-js-pure
12:23:12.995 | > node -e "try{require('./postinstall')}catch(e){}"
12:23:12.995 |  
12:23:13.111 | Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
12:23:13.111 |  
12:23:13.111 | The project needs your help! Please consider supporting of core-js:
12:23:13.111 | > https://opencollective.com/core-js
12:23:13.112 | > https://patreon.com/zloirock
12:23:13.112 | > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
12:23:13.112 |  
12:23:13.112 | Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
12:23:13.112 |  
12:23:13.357 | npm notice created a lockfile as package-lock.json. You should commit this file.
12:23:13.359 | npm WARN notsup Unsupported engine for next@12.3.1: wanted: {"node":">=12.22.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.360 | npm WARN notsup Not compatible with your version of node/npm: next@12.3.1
12:23:13.360 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm64@12.3.1 (node_modules/next/node_modules/@next/swc-android-arm64):
12:23:13.361 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm64@12.3.1: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
12:23:13.361 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm-eabi@12.3.1 (node_modules/next/node_modules/@next/swc-android-arm-eabi):
12:23:13.361 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm-eabi@12.3.1: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
12:23:13.361 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@12.3.1 (node_modules/next/node_modules/@next/swc-darwin-arm64):
12:23:13.361 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@12.3.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
12:23:13.362 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@12.3.1 (node_modules/next/node_modules/@next/swc-darwin-x64):
12:23:13.362 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@12.3.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
12:23:13.362 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-freebsd-x64@12.3.1 (node_modules/next/node_modules/@next/swc-freebsd-x64):
12:23:13.362 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-freebsd-x64@12.3.1: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
12:23:13.362 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@12.3.1 (node_modules/next/node_modules/@next/swc-linux-arm64-musl):
12:23:13.363 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@12.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
12:23:13.363 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm-gnueabihf@12.3.1 (node_modules/next/node_modules/@next/swc-linux-arm-gnueabihf):
12:23:13.363 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm-gnueabihf@12.3.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
12:23:13.363 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@12.3.1 (node_modules/next/node_modules/@next/swc-win32-arm64-msvc):
12:23:13.363 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@12.3.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
12:23:13.364 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@12.3.1 (node_modules/next/node_modules/@next/swc-linux-arm64-gnu):
12:23:13.364 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@12.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
12:23:13.364 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@12.3.1 (node_modules/next/node_modules/@next/swc-win32-ia32-msvc):
12:23:13.364 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@12.3.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
12:23:13.364 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@12.3.1 (node_modules/next/node_modules/@next/swc-win32-x64-msvc):
12:23:13.364 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@12.3.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
12:23:13.365 | npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@5.46.0: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.365 | npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@5.46.0
12:23:13.365 | npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.46.0: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.365 | npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.46.0
12:23:13.365 | npm WARN notsup Unsupported engine for eslint@8.24.0: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.365 | npm WARN notsup Not compatible with your version of node/npm: eslint@8.24.0
12:23:13.365 | npm WARN notsup Unsupported engine for eslint-plugin-promise@6.1.1: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.365 | npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-promise@6.1.1
12:23:13.366 | npm WARN notsup Unsupported engine for eslint-plugin-n@15.6.0: wanted: {"node":">=12.22.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.366 | npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-n@15.6.0
12:23:13.367 | npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.46.0: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
12:23:13.368 | npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.46.0
12:23:13.368 | npm WARN notsup Unsupported engine for @typescript-eslint/utils@5.46.0: wanted: {"node":"^12.22.0 \|\| ^14.17.0 \|\| >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
 [...]

2022-12-13 20:38 UTC, use-to commented
> 

@JannikWibker already mentioned that this error may occur frequently.

2022-12-14 17:24 UTC, use-to approved these changes

2022-12-14 17:25 UTC, JannikWibker approved these changes

2022-12-14 17:25 UTC, merged