fix: Remove other/s from organization card
helpwave/web pull request #303
Opened 2023-04-25 15:51 UTC by rajarshisamaddar

Removing other/s from the organization card has been solved in this PR.

This PR resolves issue #246 

Testing instructions:
1. Please check the organization/s card where +2 others have been replaced with only +2.

2023-04-25 16:07 UTC, florian-sabonchi approved these changes

2023-04-25 16:21 UTC, florian-sabonchi commented
![Bildschirmfoto vom 2023-04-25 18-20-29](https://user-images.githubusercontent.com/54689374/234340574-f9c864c0-48f6-4733-90da-14e646766ee7.png)
seems to be already there

2023-04-25 16:24 UTC, rajarshisamaddar commented
> ![Bildschirmfoto vom 2023-04-25 18-20-29](https://user-images.githubusercontent.com/54689374/234340574-f9c864c0-48f6-4733-90da-14e646766ee7.png) seems to be already there

Yes it was already there but I implemented it for the ICU, Radiology .... Section

2023-04-25 16:35 UTC, DasProffi commented
@rajarshisamaddar please always add the `closes #246` at the beginning of your PR so github automatically closes the issue after the PR is merged

This will also link PR and issue making it easier to track them

2023-04-25 16:40 UTC, rajarshisamaddar commented
> @rajarshisamaddar please always add the at the beginning of your PR so github automatically closes the issue after the PR is merged`closes #246`
> 
> This will also link PR and issue making it easier to track them

Okay I'll keep this in mind from now onwards

2023-04-25 16:51 UTC, MaxSchaefer requested changes
Is there any reason behind this string interpolation? I guess we can get rid of this.

2023-04-25 18:22 UTC, DasProffi commented
> Is there any reason behind this string interpolation? I guess we can get rid of this.

there is a + and a space, I think the interpolation is fine

2023-04-25 18:56 UTC, MaxSchaefer commented
> > Is there any reason behind this string interpolation? I guess we can get rid of this.
> 
> there is a + and a space, I think the interpolation is fine

@FoseFx what speaks against the following?
```jsx
<span>+ {notDisplayedProfiles}</span>
```

2023-04-25 19:43 UTC, DasProffi commented
> > > Is there any reason behind this string interpolation? I guess we can get rid of this.
> > 
> > 
> > there is a + and a space, I think the interpolation is fine
> 
> @DasProffi what speaks against the following?
> 
> ```js
> <span>+ {notDisplayedProfiles}</span>
> ```

Not much, the interpolation would allow easier modifiability if we want to change it later on, but it doesn't really matter what we choose, therefore I don't see the reason for this being a blocking change request.

2023-04-25 20:09 UTC, MaxSchaefer requested changes
Thanks! Please ensure to remove unused code. In that case the translations.

2023-04-25 20:09 UTC, MaxSchaefer commented on tasks/components/AvatarGroup.tsx
> +            <span>{`+ ${(notDisplayedProfiles)}`}</span>
```suggestion
            <span>+ {notDisplayedProfiles}</span>
```

2023-04-25 20:09 UTC, MaxSchaefer commented on tasks/components/cards/OrganizationCard.tsx
> +            {`+ ${notDisplayedWards}`}
```suggestion
            + {notDisplayedWards}
```
... and inline as well :)

2023-04-26 18:32 UTC, MaxSchaefer commented
Hey @rajarshisamaddar thanks for the changes. If you want to re-request the review please use the following button in GitHub. Looks great, can you still remove the already mentioned unused code? I feel confident that @florian-sabonchi can then merge this pr.
![Bildschirm­foto 2023-04-26 um 8 29 35 PM](https://user-images.githubusercontent.com/40192999/234669741-adab345c-6fa8-4751-a388-8dc9a9c5c2f7.png)

2023-04-26 19:53 UTC, florian-sabonchi commented
Hello @rajarshisamaddar  I have removed the translations to speed up the process

2023-04-26 20:06 UTC, MaxSchaefer approved these changes

2023-04-26 21:16 UTC, use-to commented
@florian-sabonchi please merge it if it's ready.

2023-04-27 06:07 UTC, merged

2023-04-27 07:16 UTC, rajarshisamaddar commented
> Hello @rajarshisamaddar  I have removed the translations to speed up the process

Thankyou @florian-sabonchi