Issue/271 persist lang setting
helpwave/web pull request #338
Opened 2023-05-02 18:09 UTC by Paul-B98

closes #271

2023-05-02 18:25 UTC, MaxSchaefer requested changes
In React-Land we should move this inside a Hook. What speaks against a simplified version of an [`useLocalStorage()`](https://usehooks-ts.com/react-hook/use-local-storage) or [`use-persisted-state`](https://github.com/donavon/use-persisted-state)? We can wrap `LocalStroageService` with such a hook.

2023-05-03 17:37 UTC, use-to commented
@Paul-B98 I think @MaxSchaefer wants you to throw the `StorageSerice` away.

2023-05-03 18:11 UTC, MaxSchaefer requested changes

2023-05-03 18:11 UTC, MaxSchaefer commented on lib/hooks/useLocalStorage.tsx
> +const useLocalStorage: FunctionType = <T, >(key: string, initValue: T) => {
```suggestion
const useLocalStorage = <T, >(key: string, initValue: T): [T, SetValue<T>] => {
```

2023-05-03 18:11 UTC, MaxSchaefer commented on lib/hooks/useLocalStorage.tsx
> +    if (typeof window === "undefined") {
```suggestion
    if (typeof window === 'undefined') { 
```

2023-05-03 18:23 UTC, MaxSchaefer commented
> @Paul-B98 I think @MaxSchaefer wants you to throw the `StorageSerice` away.

No, not necessarily. It's just an unusually OOP approach in our Frontend, the `hook`-Wrapper translates this very well into React-Land.

2023-05-03 21:02 UTC, MaxSchaefer approved these changes
@Paul-B98 looks good to me! Good job
I've just moved the call to `setStoredLanguage` directly into the `useLanguage`-Hook. Seams like a good idea that every call to `setLanguage` should persist the language as well.

2023-05-03 22:09 UTC, MaxSchaefer commented
@Paul-B98 I've invited you to the web-Team. You can consider a squash merge.

2023-05-04 18:23 UTC, merged