fix: swap create/update button with danger zone
helpwave/web pull request #342
Opened 2023-05-04 10:34 UTC by aegis301

2023-05-04 14:43 UTC, use-to requested changes
We need to swap it on the WardDetails too.

2023-05-05 08:10 UTC, use-to submitted a review, later dismissed

2023-05-05 14:39 UTC, Paul-B98 approved these changes

2023-05-05 20:18 UTC, MaxSchaefer approved these changes

2023-05-06 03:02 UTC, merged