fix: subtasks overflow
helpwave/web pull request #407
Opened 2023-05-13 15:22 UTC by florian-sabonchi

2023-05-13 16:05 UTC, MaxSchaefer requested changes
The alignments of the "Add Subtask" and "Update" buttons are different. They should be at the same level. I guess this is due to the fixed height.

![Bildschirm­foto 2023-05-13 um 6 04 10 PM](https://github.com/helpwave/web/assets/40192999/5fbffc21-be7e-470f-ac8e-69da71f4b4b3)

2023-05-14 16:52 UTC, Paul-B98 requested changes

2023-05-14 16:52 UTC, Paul-B98 commented on tasks/components/layout/TaskDetailView.tsx
> +          <div className={tw('flex flex-col gap-y-6 w-[60%] min-w-[500px]')}>
```suggestion
          <div className={tw('flex flex-col gap-y-8 w-[60%] min-w-[500px]')}>
```

I think this is the correct class

2023-05-14 17:53 UTC, Paul-B98 submitted a review, later dismissed

2023-05-14 18:18 UTC, MaxSchaefer requested changes
The layout shift of the whole scroll area is okay. But I guess that the layout shift of the update button is not intended.

https://github.com/helpwave/web/assets/40192999/99a0bde3-a94b-45d8-aa3f-9cba681332fa

2023-05-15 14:17 UTC, DasProffi commented on tasks/components/SubtaskView.tsx
> +   */
```suggestion
   // Automatic scrolling to the last element to give the user a visual feedback
```

2023-05-16 06:59 UTC, MaxSchaefer commented
@florian-sabonchi we should stick the button permanently to the bottom. This will prevent a layout shift.

2023-05-16 20:11 UTC, MaxSchaefer approved these changes

2023-05-16 22:23 UTC, merged