make FeatureDetails flexible
helpwave/web pull request #436
Opened 2023-05-24 11:23 UTC by DasProffi

closes #416

2023-05-24 11:24 UTC, DasProffi commented
There is a major layout shift for smaller widths, feel free to make suggestions to improve this

2023-05-28 18:58 UTC, use-to requested changes

2023-05-28 18:58 UTC, use-to commented on tasks/components/layout/FeatureDetails.tsx
> +          titleOnTop={width !== undefined ? width < 600 : undefined}
See #435

2023-05-30 01:00 UTC, use-to approved these changes

2023-05-31 19:57 UTC, merged