Proper contact us form
helpwave/web pull request #46
Opened 2023-01-12 17:32 UTC by JannikWibker

2023-01-12 17:33 UTC, JannikWibker commented
For now this draft PR is just here in order to not forget about the contact us form design
Functionality (submitting form data) will follow soon™️

2023-01-25 17:12 UTC, use-to commented
This pull-request scope is way too large. We need faster and more iterations. So others don't wait for this...
Try to finish this, please!

2023-01-25 19:44 UTC, JannikWibker commented
*that's what happens when feedback loops are too long and PR/commit/issue conventions too cumbersome*

2023-01-25 20:13 UTC, MaxSchaefer requested changes

2023-01-28 13:32 UTC, JannikWibker commented on landing-page/components/sections/ContactSection.tsx
> +      <form onSubmit={handleSubmit}>
I implemented a basic toast notification on success (and one on error in red)

2023-01-28 20:05 UTC, MaxSchaefer approved these changes
LGTM!
The contact form looks good for now. We should achieve higher UX and GDPR compliance as soon as possible. I'm preparing our HubSpot for that.

2023-01-28 20:15 UTC, merged