add patient list base
helpwave/web pull request #483
Opened 2023-07-03 19:45 UTC by DasProffi

## Which issues does this pull request close?
closes #471

## [OPTIONAL] Give testing instructions to reviewers
go to the ward screen

2023-07-04 08:16 UTC, use-to requested changes
Should we already implement the button functionalities? (`// TODO`)
Or do we slice this into smaller issues? @MaxSchaefer  
Maybe #460 is blocking.

2023-07-04 08:16 UTC, use-to commented on tasks/pages/ward/[uuid].tsx
> +          selectedBed.id === '' || selectedBed.patient === undefined || isShowingPatientDialog ? (
```suggestion
          !selectedBed.id || !selectedBed.patient || isShowingPatientDialog ? (
```

2023-07-04 21:32 UTC, MaxSchaefer commented
> Should we already implement the button functionalities? (`// TODO`) Or do we slice this into smaller issues? @MaxSchaefer Maybe #460 is blocking.

We will slice this into a smaller issue that contains all the API related stuff for this view. Its not that much but this pr should not be blocked by https://github.com/helpwave/services/issues/246

2023-07-05 14:42 UTC, use-to approved these changes

2023-07-05 17:39 UTC, merged