add WardOverview backend connection
helpwave/web pull request #486
Opened 2023-07-04 13:07 UTC by DasProffi

## Which issues does this pull request close?
closes #477
closes #478
closes #482

2023-07-07 20:33 UTC, use-to requested changes
Are these version pins related to #485 
As these changes aren't related to `tasks` we should think about moving that to #485 .

2023-07-07 20:46 UTC, use-to submitted a review, later dismissed
@DasProffi could you check this pr again? I feel like there is a version mismatch with our `helpwave/ts-proto` resulting in loading issues.

2023-07-07 21:13 UTC, MaxSchaefer requested changes
- Room creations, updates and removes are not updating the UI on the ward form
- The patient details form does not switch into the creation mode and therefore a creation of a patient is not possible
- (The patient details of an already created patient does not display. I guess this is due to the new patient list. We should track this in a new issue)

2023-07-07 21:18 UTC, MaxSchaefer commented
> @DasProffi could you check this pr again? I feel like there is a version mismatch with our `helpwave/ts-proto` resulting in loading issues.

@use-to the version is correct. The loading issue was due to https://github.com/helpwave/services/pull/253

2023-07-09 11:50 UTC, DasProffi commented
@use-to Why did you mark it as draft when I request you rereview?

2023-07-09 11:52 UTC, DasProffi commented
The rooms are updating but the current table doesn't allow for showing changes, this will be done in issue #495

2023-07-09 12:00 UTC, use-to commented
> @use-to Why did you mark it as draft when I request you rereview?

It seems to me that editing the rooms does not work. So the connection in the WardOverview is not ready yet, right? If the PR is ready-for-review, I think that everything is ready and there is no more work on it, except the request changes.

2023-07-09 12:03 UTC, use-to commented
> The rooms are updating but the current table doesn't allow for showing changes, this will be done in issue #495

Thats maybe the issue. We should fix that issue #495 first, then merge it into this branch and then set this PR to ready.

2023-07-09 13:33 UTC, MaxSchaefer commented
@DasProffi @use-to this pr is getting too large and should be merged by the end of the day. I've updated #477, the logic for room creation and updates is working fine, just state is not propagated to the UI. This should be fixed by #495 and #496 directly after this pr.

Lets review and merge this.

2023-07-09 13:40 UTC, use-to commented
> @DasProffi @use-to this pr is getting too large and should be merged by the end of the day. I've updated #477, the logic for room creation and updates is working fine, just state is not propagated to the UI. This should be fixed by #495 and #496 directly after this pr.
> 
> Let's review and merge this.

I disagree, but as we need progress - Go ahead.

2023-07-09 21:23 UTC, MaxSchaefer commented
To test the underlying logic with an implemented UI, #495 and #496 will be added to this pull request. Because of that, I will move the pull request to draft.

2023-07-09 22:16 UTC, DasProffi commented
@MaxSchaefer am I missing something that should be added with this PR or can I reopen it for review?

2023-07-09 22:24 UTC, MaxSchaefer commented
@DasProffi looks good. You can reopen this.

2023-07-10 19:40 UTC, MaxSchaefer requested changes

2023-07-10 19:40 UTC, MaxSchaefer commented on tasks/components/layout/PatientDetails.tsx
> +  const sortedTasksByPatient = (patient: PatientDetailsDTO) => ({
```suggestion
  const sortedTasksByPatient = (patient: PatientDetailsDTO) => ({
```
Pass TaskDTO directly

2023-07-10 19:40 UTC, MaxSchaefer commented on tasks/components/layout/WardDetails.tsx
> +    roomsNotOnCreate: 'Rooms can only be added once the Ward is Created'
```suggestion
    roomsNotOnCreate: 'Rooms can only be added once the ward is created'
```

2023-07-10 20:06 UTC, DasProffi commented on tasks/mutations/ward_mutations.ts
> +export const useWardUpdateMutation = (callback: (ward:WardDTO) => void) => {
no, as these functions are only internal for the react query and provide no external access to the results, this a callback is required

2023-07-10 20:23 UTC, MaxSchaefer commented
Looks good! @use-to did you plan to review as well?

2023-07-10 20:34 UTC, MaxSchaefer approved these changes

2023-07-10 20:55 UTC, use-to requested changes
[Screencast from 2023-07-10 22-52-30.webm](https://github.com/helpwave/web/assets/13922835/7c064bbb-0608-4b55-8b71-0faec20de870)

2023-07-10 21:12 UTC, use-to commented
> Looks good! @use-to did you plan to review as well?

I did now, just dismiss my review if the requested change is not part of this pr.

2023-07-11 08:15 UTC, DasProffi commented
> > Looks good! @use-to did you plan to review as well?
> 
> I did now, just dismiss my review if the requested change is not part of this pr.

yeah, this is not part of the pr for now, because the endpoint doesn't exist yet

2023-07-11 08:18 UTC, merged