updated README.md
helpwave/web pull request #49
Opened 2023-01-20 13:26 UTC by DasProffi

closes #29

2023-01-20 13:27 UTC, DasProffi commented
@florian-sabonchi did you want anything else updated?

2023-01-20 13:27 UTC, JannikWibker approved these changes

2023-01-21 15:42 UTC, florian-sabonchi approved these changes

2023-01-21 15:43 UTC, MaxSchaefer requested changes

2023-01-21 15:43 UTC, MaxSchaefer commented on README.md
> +- Helpwave web application (see [app](/app))
```suggestion
- helpwave web application (see [app](/app))
```

2023-01-21 18:44 UTC, MaxSchaefer approved these changes

2023-01-21 18:54 UTC, merged