Issue/481 crud task templates
helpwave/web pull request #497
Opened 2023-07-09 16:11 UTC by florianjs

## Which issues does this pull request close?
closes #481

Hello, in this pull request i added the backend implemenation for Task Template. Task Templates can now be created updated and delated with the backend

2023-07-10 14:34 UTC, DasProffi commented
added #480 to closes, because this PR already implements it

2023-07-10 19:57 UTC, MaxSchaefer requested changes

2023-07-10 19:57 UTC, MaxSchaefer commented on tasks/mutations/task_template_mutations.ts
>      },
This can be removed

2023-07-10 19:57 UTC, MaxSchaefer commented on tasks/mutations/task_template_mutations.ts
>      },
This can be removed

2023-07-10 19:57 UTC, MaxSchaefer commented on tasks/mutations/task_template_mutations.ts
>      },
This can be removed

2023-07-11 17:51 UTC, florianjs commented on tasks/mutations/room_mutations.ts
> +  isDone?: boolean
I would suggest leaving it at the current optional type.

2023-07-11 17:51 UTC, florianjs commented on tasks/mutations/task_template_mutations.ts
> +    id?: string,
I would suggest leaving it at the current optional type.

2023-07-11 22:36 UTC, MaxSchaefer commented on tasks/mutations/task_template_mutations.ts
> +    queryKey: ['wardTaskTemplates'],
Sorry. That's a type.

2023-07-13 17:16 UTC, closed without merging