add task kanban backend connection
helpwave/web pull request #504
Opened 2023-07-13 12:57 UTC by DasProffi

## Which issues does this pull request close?
closes #499

2023-07-13 12:58 UTC, DasProffi commented
Blocked by https://github.com/helpwave/services/issues/263

2023-07-15 15:45 UTC, use-to requested changes

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +        console.error('create room failed')
update error message

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +      }
```suggestion
      }
      
```

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +      }
update error message

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +export const useTaskToToDoMutation = (callback: () => void) => {
assign default noop callback

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +export const useTaskToInProgressMutation = (callback: () => void) => {
assign default noop callback

2023-07-15 15:45 UTC, use-to commented on tasks/mutations/task_mutations.ts
> +export const useTaskToDoneMutation = (callback: () => void) => {
assign default noop callback

2023-07-15 16:15 UTC, use-to reviewed
Works like a charm. Awaiting task creation 👍🏻

2023-07-15 16:15 UTC, use-to approved these changes
Works like a charm. Awaiting task creation 👍🏻

2023-07-15 16:44 UTC, merged

2023-07-15 18:06 UTC, MaxSchaefer commented
@DasProffi @useto the linked issue says "Create, update and delete tasks on kanban" any reason why the creation is not implemented? Or am I doing something wrong? 😅

2023-07-15 18:12 UTC, DasProffi commented
Because then the issue would be bloated, since only implementing create makes not much sense when the view has to handle read, write, update.
But also I just over read it