add: bed and room select
helpwave/web pull request #550
Opened 2023-07-29 23:44 UTC by DasProffi

## Which issues does this pull request close?
closes #473

2023-07-29 23:44 UTC, DasProffi commented
Functionality works, but the bed and room id isn't updated in the context

2023-07-30 21:18 UTC, MaxSchaefer requested changes
- Please fall back to vertical stacked inputs instead of scaling the height
- The `save` indicator is always visible
- Please add the room and bed labels above the inputs

![Bildschirm­foto 2023-07-30 um 11 15 48 PM](https://github.com/helpwave/web/assets/40192999/bdcd87f7-da6c-4540-8312-3690e770cacf)

2023-08-01 19:14 UTC, MaxSchaefer approved these changes

2023-08-01 19:54 UTC, DasProffi commented
The PR isn't updating so I will create a new one to hopefully fix this
see

2023-08-01 19:54 UTC, closed without merging