fix: rollback #526
helpwave/web pull request #581
Opened 2023-08-04 21:07 UTC by florianjs

## Which issues does this pull request close?
closes #526 

## [OPTIONAL] Give testing instructions to reviewers

2023-08-04 21:09 UTC, MaxSchaefer requested changes
https://github.com/helpwave/web/issues/526#issuecomment-1666182769

2023-08-04 21:33 UTC, DasProffi requested changes

2023-08-04 21:33 UTC, DasProffi commented on tasks/components/RoomOverview.tsx
> +      ) : ''}
Don't fix it here but in the `WardRoomList` component

2023-08-05 12:04 UTC, DasProffi approved these changes

2023-08-05 12:04 UTC, DasProffi commented on tasks/components/layout/WardRoomList.tsx
> +          ) : ''
use a filter instead
```suggestion
        {rooms && rooms.filter(room => room.beds.length > 0).map(room => ( 
            <RoomOverview
              key={room.id}
              room={room}
            />
```

2023-08-05 13:24 UTC, DasProffi approved these changes

2023-08-05 17:44 UTC, MaxSchaefer approved these changes

2023-08-05 18:24 UTC, merged