reenable isPublic for tasks
helpwave/web pull request #630
Opened 2023-08-15 11:15 UTC by DasProffi

## Which issues does this pull request close?
closes #558

The backend isn't working properly on create see https://github.com/helpwave/services/pull/359

2023-08-16 19:27 UTC, MaxSchaefer requested changes
Very nice! To points:

- [ ] A "you cannot undo this operation"-modal before going public with a task
- [ ] Re-enable the red outline of a task that is already due

2023-08-17 19:53 UTC, MaxSchaefer reviewed
I like the modal. @DasProffi after I confirmed  the modal, the tasks gets only published when I save/update the task. The UX is not quite nice. As a user I would expect that the task gets published directly after my confirmation. If this needs a large refactor, let me know.

2023-08-17 22:13 UTC, DasProffi commented
> I like the modal. @DasProffi after I confirmed the modal, the tasks gets only published when I save/update the task. The UX is not quite nice. As a user I would expect that the task gets published directly after my confirmation. If this needs a large refactor, let me know.

Yes, that's an issue for the entire task screen, see #636

2023-08-17 22:28 UTC, MaxSchaefer approved these changes

2023-08-18 06:33 UTC, merged