feat: first draft for deleting patient
helpwave/web pull request #643
Opened 2023-08-19 16:14 UTC by florianjs

## Which issues does this pull request close?
closes #618 

## [OPTIONAL] Give testing instructions to reviewers

2023-08-19 16:53 UTC, DasProffi requested changes

2023-08-19 16:53 UTC, DasProffi commented on tasks/components/layout/PatientList.tsx
>                            }
remove the now unnecessary curly brackets

2023-08-19 20:18 UTC, use-to commented on pnpm-lock.yaml
> +settings:
Revert please. I want to see those settings at the beginning of this file.

2023-08-19 20:18 UTC, use-to commented on tasks/mutations/patient_mutations.ts
> +  GetPatientListRequest, DeletePatientRequest
Formatting please

2023-08-19 20:46 UTC, use-to submitted a review, later dismissed
LGTM

2023-08-19 22:43 UTC, DasProffi approved these changes

2023-08-19 22:44 UTC, DasProffi requested changes

2023-08-19 22:44 UTC, DasProffi commented on tasks/components/layout/PatientList.tsx
> +                    </Draggable>
Discharged patients aren't draggable and cannot be clicked, please remove this

2023-08-20 11:09 UTC, DasProffi requested changes

2023-08-20 11:09 UTC, DasProffi commented on tasks/components/layout/PatientList.tsx
> +                      onClick={() => updateContext({ wardId: context.wardId, patientId: patient.id })}
Remove the on lick discharged patients aren't selectable

2023-08-20 15:17 UTC, DasProffi approved these changes

2023-08-20 15:22 UTC, merged