change the used organization header
helpwave/web pull request #652
Opened 2023-08-22 22:22 UTC by DasProffi

## Which issues does this pull request close?
closes #642

2023-08-22 22:25 UTC, DasProffi commented
This creates an error currently, because the token claims aren't set properly by the backend

2023-08-22 23:57 UTC, DasProffi commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
What do you mean?

2023-08-23 00:06 UTC, DasProffi commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
The backend expects a header and not all request like bed create could provide an organisation id. Removing the default here would mean coming up with an organization in all requests or having a dependency to backend changes.
Maybe @MaxSchaefer can provide us with the current state of the X-Organisation header

2023-08-23 23:12 UTC, MaxSchaefer commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
@DasProffi that's correct. Currently, the `X-Organization` header is required. https://github.com/helpwave/services/pull/374 is also about to introduce `3b25c6f5-4705-4074-9fc6-a50c28eba406` (demo org) as a "default"/"fallback" organization ID. As already (internal) mentioned, this behavior is of course a huge tech debt and will be addressed after a restructure of our multi-tenancy approach. cc. @helpwave/medical

2023-08-23 23:15 UTC, MaxSchaefer commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
@DasProffi please make sure to add a `// todo`.

2023-08-23 23:17 UTC, MaxSchaefer commented
@DasProffi lets hop on a call before merging.

2023-08-24 00:25 UTC, use-to commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
It's just not obvious I suggest the uuid to be the nil uuid as a default organization. These hard-coded random uuids are totally unreadable and we should document these internal communications more (mention it in the issue)

2023-08-24 00:29 UTC, use-to commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
@MaxSchaefer A demo organization should not have the same uuid for everyone, right? So why should a default uuid be hardcoded?

2023-08-24 00:29 UTC, use-to commented
> @DasProffi lets hop on a call before merging.

Yes, please. You should invite to that meeting.

2023-08-24 00:32 UTC, use-to requested changes

2023-08-24 00:32 UTC, use-to commented on tasks/components/layout/WardDetails.tsx
> +  const createWardMutation = useWardCreateMutation(organisationId, (ward) => context.updateContext({ ...context.state, wardId: ward.id }))
```suggestion
  const createWardMutation = useWardCreateMutation(organizationId, (ward) => context.updateContext({ ...context.state, wardId: ward.id }))
```

2023-08-24 00:32 UTC, use-to commented on tasks/components/layout/WardDetails.tsx
> +  const createWardMutation = useWardCreateMutation(organisationId, (ward) => context.updateContext({ ...context.state, wardId: ward.id }))
We agreed some time ago on using the american english spelling.

2023-08-24 00:32 UTC, use-to commented on tasks/utils/grpc.ts
> +const defaultOrganization = `3b25c6f5-4705-4074-9fc6-a50c28eba406`
```suggestion
const defaultOrganization = `00000000-0000-0000-0000-000000000000`
```

2023-08-26 10:29 UTC, florianjs commented
[Bildschirmaufzeichnung vom 2023-08-26, 12-28-09.webm](https://github.com/helpwave/web/assets/54689374/a665469b-842d-46dc-ae05-e4df82d433d3)

2023-08-27 17:01 UTC, MaxSchaefer commented
> Bildschirmaufzeichnung.vom.2023-08-26.12-28-09.webm 
> we should check if the user has acces to the Organisation bevor showing

Until refresh tokens. That's a very good idea. I will add a modal that asks after "Accept invite" and "Create organization" to re-login to helpwave tasks (this should happen not often). The modal has the following choices, "Yes, logout." / "No, later." with the information that the new organizations will be visible in the UI after a re-login.

2023-08-29 23:36 UTC, MaxSchaefer commented
Open to-dos
- [ ] Display "ReSignInModal" after "CreateOrganization" and "AcceptInvitation" @DasProffi 
- [ ] Hide organizations in the organizations listing that are not in the current access token @DasProffi 
- [ ] Perform merge with https://github.com/helpwave/services/pull/374 @MaxSchaefer

2023-09-01 14:11 UTC, MaxSchaefer commented
@use-to you've requested changes :) Please take a look.

2023-09-01 14:43 UTC, merged