feat: dont filter organizations during edit as well
helpwave/web pull request #701
Opened 2023-09-03 00:04 UTC by MaxSchaefer

2023-09-03 16:53 UTC, DasProffi requested changes

2023-09-03 16:53 UTC, DasProffi commented on tasks/components/layout/OrganizationDetails.tsx
> +  const isCreatingNewOrganization = contextState.organizationId === '' || !(fakeTokenEnable || organizations.includes(contextState.organizationId))
this boolean shouldn't be touched as it determines the state of creating and loading an organization.

For any change regarding showing a component based on organization claims do it seperatly?
e.g. if your intent is to show the create screen if the user doesn't has access to the organization, do it in the organization page and not in this view
```suggestion
  const isCreatingNewOrganization = contextState.organizationId === ''
```

2023-09-04 14:55 UTC, DasProffi approved these changes

2023-09-04 17:49 UTC, use-to commented
@MaxSchaefer I just fixed the linting issue. This pr is ready now!

2023-09-04 17:55 UTC, MaxSchaefer commented
> @MaxSchaefer I just fixed the linting issue. This pr is ready now!

Yeah, thanks 😅 Was a quick "Accept suggested changes"

2023-09-05 11:23 UTC, DasProffi approved these changes

2023-09-05 18:59 UTC, merged