add organization scope to patient create
helpwave/web pull request #721
Opened 2023-09-04 17:10 UTC by DasProffi

## Which issues does this pull request close?
closes #707

2023-09-05 12:04 UTC, use-to requested changes
Could we extend this pr adding this to the query as well. So we finish #663 #711 #691 too?!

2023-09-06 18:12 UTC, florianjs approved these changes

2023-09-06 18:13 UTC, florianjs commented
Looks good to me

2023-09-07 20:36 UTC, use-to approved these changes

2023-09-07 20:43 UTC, merged