add patient readmit mutation
helpwave/web pull request #739
Opened 2023-09-24 12:14 UTC by DasProffi

## Which issues does this pull request close?
closes #736

2023-09-29 16:39 UTC, use-to approved these changes
Just some weird import formatting

2023-09-29 16:39 UTC, use-to commented on tasks/mutations/patient_mutations.ts
> +  DeletePatientRequest, ReadmitPatientRequest
```suggestion
  DeletePatientRequest,
  ReadmitPatientRequest
```

2023-09-29 16:39 UTC, use-to commented on tasks/pages/ward/[id].tsx
> +  usePatientDischargeMutation, useReadmitPatientMutation,
```suggestion
  usePatientDischargeMutation,
  useReadmitPatientMutation
```

2023-09-29 16:55 UTC, use-to requested changes
Dragging discharged patients onto empty bed cards is not working.

2023-09-29 19:42 UTC, DasProffi commented
> Dragging discharged patients onto empty bed cards is not working.

Are you on the most recent version of the branch? For me, it works

2023-09-29 19:45 UTC, DasProffi commented
> > Dragging discharged patients onto empty bed cards is not working.
> 
> Are you on the most recent version of the branch? For me, it works

Never mind, the error now also occurs for me, but seems timing related

2023-09-30 18:52 UTC, use-to approved these changes
Restarted Cloudflare build. LGTM now!

2023-09-30 20:29 UTC, merged