add recent patients
helpwave/web pull request #744
Opened 2023-10-02 14:38 UTC by DasProffi

## Which issues does this pull request close?
closes #740

2023-10-05 11:25 UTC, use-to requested changes
Currently unable to test it against the backend. It just returns an empty set of patients.
Also, please consider removing the organization sections (so only recent patient and wards will be shown). It not so important to navigate to the organization overview page all the time.

2023-10-05 11:25 UTC, use-to commented on tasks/mutations/room_mutations.ts
> +  GetRoomOverviewsByWardRequest, GetRoomRequest,
```suggestion
  GetRoomOverviewsByWardRequest,
  GetRoomRequest,
```

2023-10-05 11:25 UTC, use-to commented on tasks/mutations/patient_mutations.ts
> +  ReadmitPatientRequest, GetRecentPatientsRequest
Please fix your formatter.

```suggestion
  ReadmitPatientRequest,
  GetRecentPatientsRequest
```

2023-10-05 22:21 UTC, MaxSchaefer requested changes
I've debugged this. Seams like services on Staging (and probably on production as well) has problems with the redis interaction.

For now, I added a recent patient by hand that you can move. `GetRecentPatients` is now returning one recent patient. The frontend does load and then fails silenty, can you please check this @DasProffi?

2023-10-08 15:30 UTC, MaxSchaefer commented
@DasProffi linter 👀

2023-10-09 11:42 UTC, MaxSchaefer commented
@DasProffi please re-request my review when the requested changes got addressed. Before we merge this, we need to hide the recent patients until https://github.com/helpwave/services/issues/458 is resolved.

2023-10-09 17:40 UTC, MaxSchaefer commented
> @DasProffi please re-request my review when the requested changes got addressed. Before we merge this, we need to hide the recent patients until [helpwave/services#458](https://github.com/helpwave/services/issues/458) is resolved.

@DasProffi EDIT: We can hide the title on an empty response instead.

2023-10-10 17:41 UTC, DasProffi commented
> @DasProffi EDIT: We can hide the title on an empty response instead.

Problem is addressed, the query update once the backend is fixed will be done in #754

2023-10-16 21:24 UTC, MaxSchaefer approved these changes

2023-10-16 21:27 UTC, MaxSchaefer commented
@use-to requested changes :)

2023-10-17 06:14 UTC, use-to approved these changes

2023-10-17 10:02 UTC, merged