feat: first draft for cookie consent banner
helpwave/web pull request #787
Opened 2023-10-28 08:47 UTC by florian-sabonchi

## Which issues does this pull request close?
closes #765

## [OPTIONAL] marked as draft because we need to check which cookies are used

2023-10-28 16:41 UTC, use-to requested changes
![image](https://github.com/helpwave/web/assets/13922835/192967ae-c303-4ced-86c3-9c3852ca67b6)

2023-10-28 18:09 UTC, florian-sabonchi commented
> ![image](https://user-images.githubusercontent.com/13922835/278825925-192967ae-c303-4ced-86c3-9c3852ca67b6.png)

Please not as screenshot

2023-10-29 09:48 UTC, use-to commented
> > ![image](https://user-images.githubusercontent.com/13922835/278825925-192967ae-c303-4ced-86c3-9c3852ca67b6.png)
> 
> Please not as screenshot

What do you mean? Do you need further explanation?

The links at the bottom of our footer should be removed. Instead, try to integrate it in to the footer section. (`General`)

2023-10-31 22:58 UTC, MaxSchaefer commented on landing-page/components/CookieConsentConfig.tsx
This file does not contain a component. Utils or `CookieConsent.tsx`?

2023-10-31 22:59 UTC, MaxSchaefer commented
@florian-sabonchi as already mentioned, please add the cookie settings into the general section of the footer.

2023-11-02 23:02 UTC, MaxSchaefer commented on landing-page/components/CookieConsentConfig.tsx
@florian-sabonchi this is still no component.

2023-11-03 18:31 UTC, use-to requested changes

2023-11-04 17:32 UTC, use-to approved these changes
Squash, please.

2023-11-04 17:33 UTC, use-to commented
@MaxSchaefer Any concerns?

2023-11-04 17:54 UTC, MaxSchaefer approved these changes
Very nice!

In the future, we need to add AnchorFM (Podcast) and Cloudflare (cdn.helpwave.de) to our privay policy as well.

2023-11-04 18:16 UTC, merged

2023-11-04 18:50 UTC, use-to commented
> Very nice!
> 
> In the future, we need to add AnchorFM (Podcast) and Cloudflare (cdn.helpwave.de) to our privay policy as well.

Already did in https://cdn.helpwave.de/privacy.html
We don't have to add it to the cookie banner in this case.