implements a dropdown for the task visibility options on create
helpwave/web pull request #804
Opened 2023-11-17 18:04 UTC by PaulKalho

## Which issues does this pull request close?
closes #799 

![image](https://github.com/helpwave/web/assets/67231903/1f511633-e6b3-41f7-a3b6-24672a05d8b2)

2023-11-18 21:14 UTC, florian-sabonchi submitted a review, later dismissed

2023-11-19 14:20 UTC, use-to requested changes

2023-11-19 14:20 UTC, use-to commented on tasks/components/layout/TaskDetailView.tsx
> +    </div >
```suggestion
    </div>
```

2023-11-19 14:20 UTC, use-to commented on tasks/components/layout/TaskDetailView.tsx
> +    </div >
Use a formatter like prettier

2023-11-20 10:50 UTC, use-to approved these changes

2023-11-20 13:45 UTC, merged