feat: add OrganizationSwitchModal
helpwave/web pull request #840
Opened 2024-01-27 19:18 UTC by MaxSchaefer

## Which issues does this pull request close?
closes #793 

## [OPTIONAL] Give testing instructions to reviewers

2024-01-28 00:33 UTC, MaxSchaefer commented
@DasProffi @00100200345

2024-01-28 11:21 UTC, use-to requested changes

2024-01-28 11:21 UTC, use-to commented on tasks/components/layout/PageWithHeader.tsx
> +  const organizationName = (organization?.shortName && <Span onClick={() => setOrganization(undefined)}>{organization.shortName}</Span>)
```suggestion
  const organizationName = (organization?.shortName && <Span onClick={() => setOrganization(undefined)} className={tw('cursor-pointer hover:cursor-pointer')}>{organization.shortName}</Span>)
```

2024-01-28 15:38 UTC, use-to commented
@MaxSchaefer This is still a draft. Why?

2024-01-28 15:41 UTC, use-to requested changes
The loaded view disappears, when clicking. This should not be the case.																																																																																																																																																																																																																																																																																																																																																																																																																																																																												
																																																																																																																																		
[background-reset.webm](https://github.com/helpwave/web/assets/13922835/33062a7d-a893-41cc-a925-45f9861d639f)

2024-01-28 19:37 UTC, use-to requested changes
Several issues need addressing in this code. Firstly, the complete page reload is cumbersome. Can we explore alternatives?
Secondly, when opening the modal, the current selection disappears along with the button that was just clicked.

2024-01-28 21:14 UTC, MaxSchaefer commented on tasks/hooks/useOrganization.tsx
> +          window.location.reload()
@JannikWibker the `window.location.reload()` is far from okay. I've tried to use `queryClient.clear()` and `queryClient.refechQueries()`, no effects. Can you take a look?

2024-02-03 20:40 UTC, use-to requested changes
![image](https://github.com/helpwave/web/assets/13922835/4d83b011-397a-4124-92fb-ea94255e2029)

2024-02-08 20:48 UTC, use-to requested changes
Bug still present. See image of the review before.

2024-02-09 00:06 UTC, MaxSchaefer commented
Preview didnt catched up ...
Ready on preview.

2024-02-09 11:46 UTC, use-to approved these changes
Yes, my fault. Didn't recognize that.

2024-02-09 19:10 UTC, merged