endorsement page
helpwave/web pull request #869
Opened 2024-02-14 01:36 UTC by DasProffi

## Which issues does this pull request close?
closes #867

## [OPTIONAL] Give testing instructions to reviewers

2024-02-18 23:48 UTC, MaxSchaefer commented
@DasProffi I like this page a lot! Already good on visual. What about the text?

2024-02-19 00:06 UTC, DasProffi commented
> @DasProffi I like this page a lot! Already good on visual. What about the text?
> 

The text isn't defined yet, therefore I didn't add it, but I can add placeholders for now to see the design

2024-02-20 19:06 UTC, use-to commented
Also, the mobile version is still a little bit buggy. We should also add a `press` option as a newsletter option.

2024-02-22 17:17 UTC, use-to requested changes
Please apply the following changes:
- [x] Move/Rename this site to `/join`
- [x] Remove the mock goals (see below)
- [ ] Link this page on the landing page and rename the `Discover Our Vision` button to `Subscribe` (or similar)
- [ ] Remove the `Try our demo!` button

2024-02-22 17:17 UTC, use-to commented on landing-page/pages/newsletter/index.tsx
> +                <Span className={tw(`absolute z-[100] top-1/2 left-[${sizeCircle2 + (sizeCircle3 - sizeCircle2) / 2}px] -translate-x-1/2 -translate-y-1/2 text-white mobile:hidden`)}>Goal 2</Span>
Lets hide these goals for now.
```suggestion
                <Span className={tw(`absolute z-[100] top-1/2 left-[${sizeCircle2}px] -translate-x-1/2 -translate-y-1/2 text-white mobile:hidden`)}></Span>
                <Span className={tw(`absolute z-[100] top-1/2 left-[${sizeCircle2 + (sizeCircle3 - sizeCircle2) / 2}px] -translate-x-1/2 -translate-y-1/2 text-white mobile:hidden`)}></Span>
```

2024-02-22 20:59 UTC, use-to approved these changes
Good job 👏

2024-02-22 20:59 UTC, merged