product call to action button
helpwave/web pull request #872
Opened 2024-02-14 18:23 UTC by DasProffi

## Which issues does this pull request close?
closes #868

## [OPTIONAL] Give testing instructions to reviewers

2024-02-15 09:52 UTC, use-to approved these changes

2024-02-15 09:58 UTC, use-to requested changes

2024-02-15 09:58 UTC, use-to commented on lib/components/DescriptionWithAction.tsx
> +    <div className={tx('rounded-lg bg-white flex flex-row gap-x-1 py-2 px-4', className)}>
```suggestion
    <div className={tx('rounded-lg bg-white flex flex-row gap-x-1 py-8 px-16', className)}>
```

2024-02-15 19:41 UTC, MaxSchaefer submitted a review, later dismissed

2024-02-17 10:49 UTC, MaxSchaefer commented
@use-to check your requested changes please :)

2024-02-17 12:00 UTC, use-to requested changes
![image](https://github.com/helpwave/web/assets/13922835/803201a2-8f96-4888-9632-27d8f2caa018)
Content overlap.

2024-02-18 08:40 UTC, use-to approved these changes

2024-02-18 12:59 UTC, merged