add property details
helpwave/web pull request #904
Opened 2024-03-02 13:47 UTC by DasProffi

## Which issues does this pull request close?
closes #883

## [OPTIONAL] Give testing instructions to reviewers
1. Open the tasks page
2. Look at `/properties`

2024-03-05 23:06 UTC, MaxSchaefer commented
On my To-do for today (06.03)

2024-03-06 21:51 UTC, MaxSchaefer requested changes
Pretty nice! Love to see this feature comes together! But still many things to to 👀
Some fields are not displayed during edit but I see `/properties` as a playground for integration right now. Therefore, lets not merge this against `main` but against `integration/properties`. We will consolidate approved changes on this pull request (I will create the corresponding branch protection).

For now, review the suggested changes please and we coordinate the first merge against `integration/properties` together. Great work! 🙌

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetails.tsx
Archive property button
![Bildschirmfoto 2024-03-06 um 9 26 41 PM](https://github.com/helpwave/web/assets/40192999/52000512-f29b-4452-a814-0bcf8f6517c8)

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsField.tsx
> +        options={fieldTypeList.map(fieldType => ({ value: fieldType, label: translation[fieldType] }))}
Same translation "issue" as mentioned in `PropertySubjectTypeSelect`

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsField.tsx
> +                newList.push(translation.newEntry)
`translation.newEntry` is not a correct value to push. If you want to display `New entry`, use `placeholder="..."`. An empty value in this list should really be empty/null.

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsField.tsx
> +                  <Input
As mentioned above. Use `placeholder="..."` for displaying `New entry`

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsField.tsx
> +      />
Also a part of multi-/single-selects

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsField.tsx
fyi: In the future, this component could also contain an example representation of the resulting property type as displayed on the subjects details.

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDetailsRules.tsx
> +      />
Soft-Required will be a checkbox as similar to always visible. You can use `Gets visually highlighted on an entity if the property is empty.`

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDisplay.tsx
> +            description={{ value: translation[property.field.fieldType] }}
Same "translation"-Issue as already mentioned

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDisplay.tsx
> +            key="cell-1"
```suggestion
            key="field-type-cell"
```

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDisplay.tsx
> +          (<div key="cell-2" className={tw('flex flex-row gap-x-2')}>
```suggestion
          (<div key={`subject-type-cell`} className={tw('flex flex-row gap-x-2')}>
```

2024-03-06 21:51 UTC, MaxSchaefer commented on tasks/components/layout/property/PropertyDisplay.tsx
> +          (<div key="cell-3" className={tw('flex flex-row justify-end')}>
```suggestion
          (<div key="edit-button-cell" className={tw('flex flex-row justify-end')}>
```
Do we really need all these keys?

2024-03-07 13:16 UTC, DasProffi commented on lib/components/layout/Tile.tsx
The `Card` is the layouting around the content and the click handling, the `Tile` would be used for the inside to order components with a title, description, prefix, suffix etc.

2024-03-07 13:45 UTC, DasProffi commented on tasks/components/layout/property/PropertySubjectTypeSelect.tsx
> +        label: translation[subjectType]
> Do you know any other parts in our codebase were this occurs already?

Not that I am aware of

2024-03-09 13:20 UTC, MaxSchaefer reviewed
LGTM! Translations will be an upcoming todo for our medical team.

2024-03-09 13:30 UTC, MaxSchaefer approved these changes
I switched the base branch and configured a branch ruleset. Ready for merge!

2024-03-09 13:58 UTC, DasProffi commented on tasks/components/layout/property/PropertyDetailsField.tsx
> +    </InputGroup>
That would have introduced which a large `<>...</>` bracketing which might not be as readable as this

2024-03-09 14:04 UTC, DasProffi commented
@MaxSchaefer the status does not seem to pass/progress

2024-03-09 23:47 UTC, merged