update and fix boilerplate generation script
helpwave/web pull request #926
Opened 2024-03-09 13:56 UTC by DasProffi

## Which issues does this pull request close?
closes #925

## [OPTIONAL] Give testing instructions to reviewers

2024-03-10 19:33 UTC, MaxSchaefer requested changes
- Please provide some example commands in the `README`
- Error during execution
```shell
❯ node scripts/generate_boilerplate.js Username
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at Object.<anonymous> (/Users/maxrs/Projects/helpwave/helpwave-web/scripts/generate_boilerplate.js:44:21)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

2024-03-10 19:33 UTC, MaxSchaefer commented on scripts/package.json
> +  "description": "A collection of scripts used for programming with helpwave",
```suggestion
  "description": "A collection of custom tooling for helpwave/web.",
```

2024-03-13 20:22 UTC, DasProffi commented
@MaxSchaefer same CI issue here and I have rewritten the script so that it should work

2024-03-13 21:00 UTC, MaxSchaefer requested changes
Runs now. Thanks!
`node scripts/generate_boilerplate.js -f -nop -notl tasks/components/Username`
`-notl` works fine. `-nop` should also remove the `UsernameProps` type.

```tsx
import { tw } from '@helpwave/common/twind'

export type UsernameProps = Record<string, never>

/**
 * Description
 */
export const Username = ({
} : UsernameProps) => {
  return (
    <div>
      { /* Your Code */ }
    </div>
  )
}

```

2024-03-14 23:35 UTC, MaxSchaefer approved these changes

2024-03-14 23:37 UTC, merged