feat: add placeholderbrand page
helpwave/web pull request #977
Opened 2024-04-07 01:28 UTC by DasProffi

## Which issues does this pull request close?
closes #974

## [OPTIONAL] Give testing instructions to reviewers
Open the `/placeholderbrand` page

2024-04-07 01:30 UTC, DasProffi commented
- [ ] Personal Contacts with Profiles have to be added

2024-04-09 21:14 UTC, MaxSchaefer requested changes
![Bildschirmfoto 2024-04-09 um 11 12 42 PM](https://github.com/helpwave/web/assets/40192999/8a31a669-50c7-4038-a5a8-20923d14a404)

Please check out the spacing of the headers

2024-04-09 21:14 UTC, MaxSchaefer commented on landing-page/pages/placeholderbrand/index.tsx
> +            /* TODO fectch entries */
```suggestion
```
No fetch needed. We will hardcode the FAQ.

2024-04-10 14:43 UTC, DasProffi commented
> Please check out the spacing of the headers

What spacing are you refering to?
- the horizontal padding
- the title and subtitle (which start at the same horizontal position)

2024-04-10 15:16 UTC, MaxSchaefer commented
> > Please check out the spacing of the headers
> 
> What spacing are you refering to?
> 
> * the horizontal padding
> * the title and subtitle (which start at the same horizontal position)

The 

> > Please check out the spacing of the headers
> 
> What spacing are you refering to?
> 
> * the horizontal padding
> * the title and subtitle (which start at the same horizontal position)

@DasProffi spacing between title-and-subtitle and content (like profiles and faqs)

2024-04-10 15:51 UTC, MaxSchaefer approved these changes

2024-04-11 09:44 UTC, merged