add contact page
helpwave/web pull request #987
Opened 2024-04-12 12:46 UTC by DasProffi

## Which issues does this pull request close?
closes #984

## [OPTIONAL] Give testing instructions to reviewers

2024-04-15 00:03 UTC, MaxSchaefer requested changes
Please integrate `<LoadingButton/>` for UX during form sending

2024-04-17 22:38 UTC, MaxSchaefer approved these changes
Please show "Danke für deine Nachricht!" / "Thanks for your message!" in the button after a successful submission.

2024-04-18 10:00 UTC, DasProffi commented
@MaxSchaefer I have moved the response text above or below the button, so that users aren't confused. Would you still prefer your solution or the one I provided now?

2024-04-18 10:26 UTC, MaxSchaefer approved these changes

2024-04-18 13:39 UTC, merged